version: '2'
services:
  redis-cluster:
    environment:
     IP: ${REDIS_CLUSTER_IP}
     SENTINEL: ${REDIS_USE_SENTINEL}
     STANDALONE: ${REDIS_USE_STANDALONE}
    build:
      context: .
      args:
        redis_version: '7.0.10'
    hostname: server
    ports:
      - '9000-9050:9000-9050'
      - '5020-5030:5020-5030'
